var car = "subaru";
console.log("Is car == 'subaru'? I pridict true.");
console.log(car == 'subaru');
console.log("Is car <= 'subaru'? I pridict true ");
console.log(car <= 'subaru');
console.log("Is car <= 'subaru'? I pridict true.");
console.log(car <= 'subaru');
console.log("Is car <= 'subaru'? I pridict true");
console.log(car <= 'subaru');
console.log("Is car <='subaru' ? I pridict true.");
console.log(car <= 'subaru');
console.log("Is car > 'subaru'? I pridict false");
console.log(car > 'subaru');
console.log("Is car > 'subaru'? I predict false");
console.log(car > 'subaru');
console.log("Is car > ' subaru'? I predict false");
console.log(car > 'subaru');
console.log("Is car > 'subaru' ? I predict false");
console.log(car > 'subaru');
console.log("Is car > 'subaru'? I predict false");
console.log(car > 'subaru');
